name: Deploy Frontend and Backend to Vercel

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  # pull_request:
  #   branches:
  #     - main  # Optionally trigger on pull requests to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js for frontend and backend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Ensure Node.js matches your project requirements

      # Step 3: Install dependencies and deploy frontend
      - name: Deploy Frontend
        working-directory: ./frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm install
          npm run build
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN

      # Step 4: Install dependencies and deploy backend
      - name: Deploy Backend
        working-directory: ./backend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN
